name: Weekly GitHub Profile Summary Update

on:
  schedule:
    - cron: '0 5 * * 1'  # Her Pazartesi 08:00 (Türkiye saati)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install

      - name: Generate screenshot
        run: python capture.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🔄 Weekly profile summary update
          file_pattern: profile_summary.png
