name: Günlük GitHub Profil Özeti Güncelle

on:
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Playwright kurulumu
        run: |
          pip install playwright
          playwright install

      - name: PNG oluştur
        run: python capture.py

      - name: Değişiklikleri commitle
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile_summary.png
          git commit -m "🔄 Profil özeti güncellendi" || echo "No changes"
          git push
